# frozen_string_literal: true

source 'https://rubygems.org'

gem 'awspec'
gem 'confidante'
gem 'git'
gem 'rake'
gem 'rake_circle_ci'
gem 'rake_github'
gem 'rake_gpg'
gem 'rake_ssh'
gem 'rake_terraform'
gem 'rspec'
gem 'rspec-terraform'
gem 'rubocop', '>= 1.42.0'
gem 'rubocop-rake'
gem 'rubocop-rspec', '>= 2.17.0'
gem 'rubyzip'
gem 'semantic'
