# frozen_string_literal: true

source 'https://rubygems.org'

gem 'awspec', '>= 1.29.0'
gem 'confidante'
gem 'git'
gem 'rake'
gem 'rake_circle_ci'
gem 'rake_github'
gem 'rake_gpg'
gem 'rake_ssh'
gem 'rake_terraform'
gem 'rspec'
gem 'rspec-terraform'
gem 'rubocop'
gem 'rubocop-rake'
gem 'rubocop-rspec'
gem 'rubyzip'
gem 'semantic'
